name: Terraform Deploy S3

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar configuração Terraform
        run: terraform validate

      - name: Gerar plano Terraform
        run: terraform plan -var-file=terraform.tfvars

      - name: Aplicar plano Terraform (somente branch main)
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -var-file=terraform.tfvars
